In [3]:
import pandas as pd
from sqlalchemy import create_engine


engine = create_engine("mysql+pymysql://root:@localhost/zomato_db")

df = pd.read_sql("SELECT * FROM restaurants", engine)

print(df.head())

   id         name       city  rating  cost
0   1    Pizza Hut  Ahmedabad     4.3   600
1   2      Dominos      Surat     4.1   500
2   3          KFC   Vadodara     4.2   550
3   4  Burger King     Rajkot     4.0   450
4   5       Subway  Ahmedabad     4.4   400

In [4]:
engine=create_engine("mysql+pymysql://root:@localhost/zomato_db")

df1=pd.read_sql("SELECT * FROM movies",engine)

query= "SELECT name , rating FROM movies WHERE rating>8"

df=pd.read_sql_query(query,engine)  
df

            name  rating
0  KGF Chapter 2     8.5
1       3 Idiots     8.4
2            RRR     8.8
3         Dangal     8.3
4       Drishyam     8.2

In [5]:
url="https://jsonplaceholder.typicode.com/users"

df=pd.read_json(url)

df1=pd.DataFrame(df)
df1

df1["username"]

0                Bret
1           Antonette
2            Samantha
3            Karianne
4              Kamren
5    Leopoldo_Corkery
6        Elwyn.Skiles
7       Maxime_Nienow
8            Delphine
9      Moriah.Stanton
Name: username, dtype: str

In [20]:
'''You have two CSV files: 'orders.csv' (order_id, user_id, amount) and 'users.csv' 
(user_id, username). 
    Load both into DataFrames using pathlib for file paths, 
    then merge them on 'user_id' to show a combined table with username and amount.'''
   
from pathlib import Path 
orders_data = {
    "order_id": [101, 102, 103, 104],
    "user_id": [1, 2, 1, 3],
    "amount": [500, 750, 300, 900]
}
orders = pd.DataFrame(orders_data)
orders.to_csv("orders.csv", index=False)

users_data = {
    "user_id": [1, 2, 3],
    "username": ["Rahul", "Priya", "Amit"]
}
users = pd.DataFrame(users_data)
users.to_csv("users.csv",index=False)

orders_path=Path('orders.csv')
users_path=Path('users.csv')

merge=pd.merge(orders,users,on='user_id')
merge

   order_id  user_id  amount username
0       101        1     500    Rahul
1       102        2     750    Priya
2       103        1     300    Rahul
3       104        3     900     Amit

In [ ]:
today_orders = pd.DataFrame({
    "order_id": [101, 102],
    "item": ["Pizza", "Burger"],
    "price": [250, 150]
})
yesterday_orders = pd.DataFrame({
    "order_id": [99, 100],
    "item": ["Sandwich", "Pasta"],
    "price": [100, 200]
})

combined=pd.concat([today_orders,yesterday_orders]) .reset_index(drop=True)
combined

   index  order_id      item  price
0      0       101     Pizza    250
1      1       102    Burger    150
2      0        99  Sandwich    100
3      1       100     Pasta    200