In [1]:
import pandas as pd 

df=pd.read_csv(r"C:\Users\NITU\OneDrive\Desktop\Data Science\Assignments\IPL.csv")
df.head()

C:\Users\NITU\AppData\Local\Temp\ipykernel_32268\1199609237.py:3: DtypeWarning: Columns (0: review_batter, 1: team_reviewed, 2: review_decision, 3: umpire, 4: season, 5: superover_winner, 6: result_type, 7: method, 8: event_match_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\NITU\OneDrive\Desktop\Data Science\Assignments\IPL.csv")

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,striker_out,next_batter
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0.1,...,1,0,NaN,NaN,0,1,0,BB McCullum|SC Ganguly,0,NaN
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0.2,...,2,0,NaN,NaN,0,1,0,BB McCullum|SC Ganguly,0,NaN
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,2,0,NaN,NaN,0,1,0,BB McCullum|SC Ganguly,0,NaN
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0.3,...,3,0,NaN,NaN,0,2,0,BB McCullum|SC Ganguly,0,NaN
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0.4,...,4,0,NaN,NaN,0,3,0,BB McCullum|SC Ganguly,0,NaN

In [2]:
url = "https://raw.githubusercontent.com/mhollingshead/billboard-hot-100/main/recent.json"
df = pd.read_json(url)
df.columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    100 non-null    datetime64[us]
 1   data    100 non-null    object
dtypes: datetime64[us](1), object(1)
memory usage: 1.7+ KB

In [3]:

data = {
    "Restaurant_Name": ["Domino's Pizza", "Pizza Hut", "Subway"],
    "City": ["Ahmedabad", "Surat", "Vadodara"],
    "Rating": [4.3, 4.1, 4.0],
    "Cuisine": ["Pizza", "Italian", "Fast Food"],
    "Cost": [500, 700, 350]
}

df = pd.DataFrame(data)
df.to_csv("zomato.tsv", sep="\t", index=False)

df = pd.read_csv("zomato.tsv", sep="\t")
df.describe(include='all')

       Restaurant_Name       City    Rating Cuisine        Cost
count                3          3  3.000000       3    3.000000
unique               3          3       NaN       3         NaN
top     Domino's Pizza  Ahmedabad       NaN   Pizza         NaN
freq                 1          1       NaN       1         NaN
mean               NaN        NaN  4.133333     NaN  516.666667
std                NaN        NaN  0.152753     NaN  175.594229
min                NaN        NaN  4.000000     NaN  350.000000
25%                NaN        NaN  4.050000     NaN  425.000000
50%                NaN        NaN  4.100000     NaN  500.000000
75%                NaN        NaN  4.200000     NaN  600.000000
max                NaN        NaN  4.300000     NaN  700.000000

In [4]:
import pandas as pd


df = pd.read_excel("Flipkart Sales Dataset.xls")
df
chunk_size = 2000


for i in range(0, len(df), chunk_size):
    chunk = df.iloc[i:i+chunk_size]
    print(f"Chunk {i//chunk_size + 1}: {len(chunk)} rows")

Chunk 1: 2000 rows
Chunk 2: 2000 rows
Chunk 3: 2000 rows
Chunk 4: 2000 rows
Chunk 5: 2000 rows
Chunk 6: 2000 rows
Chunk 7: 2000 rows
Chunk 8: 2000 rows
Chunk 9: 2000 rows
Chunk 10: 2000 rows
Chunk 11: 2000 rows
Chunk 12: 2000 rows
Chunk 13: 2000 rows
Chunk 14: 2000 rows
Chunk 15: 2000 rows
Chunk 16: 2000 rows
Chunk 17: 2000 rows
Chunk 18: 2000 rows
Chunk 19: 2000 rows
Chunk 20: 2000 rows
Chunk 21: 2000 rows
Chunk 22: 2000 rows
Chunk 23: 2000 rows
Chunk 24: 2000 rows
Chunk 25: 2000 rows
Chunk 26: 2000 rows
Chunk 27: 2000 rows
Chunk 28: 2000 rows
Chunk 29: 2000 rows
Chunk 30: 2000 rows
Chunk 31: 2000 rows
Chunk 32: 2000 rows
Chunk 33: 2000 rows
Chunk 34: 2000 rows
Chunk 35: 2000 rows
Chunk 36: 2000 rows
Chunk 37: 2000 rows
Chunk 38: 2000 rows
Chunk 39: 2000 rows
Chunk 40: 2000 rows
Chunk 41: 2000 rows
Chunk 42: 2000 rows
Chunk 43: 2000 rows
Chunk 44: 2000 rows
Chunk 45: 2000 rows
Chunk 46: 2000 rows
Chunk 47: 2000 rows
Chunk 48: 2000 rows
Chunk 49: 2000 rows
Chunk 50: 2000 rows
Chunk 51: 2000 rows
Chunk 52: 2000 rows
Chunk 53: 2000 rows
Chunk 54: 2000 rows
Chunk 55: 2000 rows
Chunk 56: 2000 rows
Chunk 57: 2000 rows
Chunk 58: 2000 rows
Chunk 59: 2000 rows
Chunk 60: 2000 rows
Chunk 61: 2000 rows
Chunk 62: 2000 rows
Chunk 63: 2000 rows
Chunk 64: 2000 rows
Chunk 65: 2000 rows
Chunk 66: 2000 rows
Chunk 67: 1503 rows

In [5]:
import pandas as pd
df=pd.read_csv("Paytm data.csv",sep=';')
print(df)

print("Detected null values",df.isnull().sum())

print("Columns having null values :",df.columns[df.isnull().any()])

  Transaction_ID Customer  Amount Payment_Mode   Status
0         TXN001     Nitu   500.0          UPI  Success
1         TXN002    Rahul     NaN       Wallet  Success
2         TXN003    Priya  1200.0          NaN   Failed
3         TXN004     Amit   800.0          UPI      NaN
4         TXN005    Sneha   650.0         Card  Success
Detected null values Transaction_ID    0
Customer          0
Amount            1
Payment_Mode      1
Status            1
dtype: int64
Columns having null values : Index(['Amount', 'Payment_Mode', 'Status'], dtype='str')