In [12]:
'''1.
Download a small sample of your recent Zomato order history as a 
CSV (or create a mock CSV with restaurant names and order dates), then use pandas' duplicated() function to find and 
print any duplicate orders based on restaurant name and date.'''

import pandas as pd

df=pd.read_csv('restaurant_orders.csv')
duplicates = df[df.duplicated(subset=['Restaurant_Name', 'Order_Date'],keep=False)]
duplicates

   Restaurant_Name  Order_Date
0     Spice Garden  2026-08-01
1     Spice Garden  2026-08-01
3       Urban Cafe  2026-08-02
4       Urban Cafe  2026-08-02
7    Food Junction  2026-08-05
8    Food Junction  2026-08-05
10    Pizza Corner  2026-08-08
11    Pizza Corner  2026-08-08

In [ ]:
df=pd.read_csv("flipkart_product.csv")
duplicates=(df['Review_Text'].value_counts().head(3))
duplicates

Review_Text
Not bad, but packaging could be better.    938
Fast delivery and good packaging.          926
Amazing product, I would recommend it.     916
Name: count, dtype: int64

In [ ]:
data = {
    'playlist_name': [
        'Bollywood Hits',
        'Chill Vibes',
        'Workout Mix',
        'Bollywood Hits',
        'Party Songs',
        'Chill Vibes',
        'Workout Mix',
        'Road Trip',
        'Party Songs',
        'Chill Vibes'
    ],
    'creator_username': [
        'rahul_music',
        'priya_23',
        'amit_singh',
        'rahul_music',  
        'neha_playlist',
        'priya_23',         
        'amit_singh',       
        'rohan_music',
        'neha_playlist',   
        'priya_23'         
    ]
}
df = pd.DataFrame(data)
df.drop_duplicates()
df

    playlist_name creator_username
0  Bollywood Hits      rahul_music
1     Chill Vibes         priya_23
2     Workout Mix       amit_singh
3  Bollywood Hits      rahul_music
4     Party Songs    neha_playlist
5     Chill Vibes         priya_23
6     Workout Mix       amit_singh
7       Road Trip      rohan_music
8     Party Songs    neha_playlist
9     Chill Vibes         priya_23

In [ ]:
data = {
    'username': [
        'insta_queen',
        'insta-queen',
        'instaqueen',
        'travel_lover',
        'travel-lover',
        'foodie_world',
        'foodieworld',
        'tech_guru',
        'tech-guru'
    ]
}
df = pd.DataFrame(data)
df['username']=df['username'].replace({'insta_queen':'instaqueen' , 'insta-queen':'instaqueen' , 'instaqueen':'instaqueen'})
df

       username
0    instaqueen
1    instaqueen
2    instaqueen
3  travel_lover
4  travel-lover
5  foodie_world
6   foodieworld
7     tech_guru
8     tech-guru

In [ ]:
data = {
    'payment_status': [
        'Yes',
        ' yes ',
        'Y',
        ' No',
        'no ',
        'N',
        ' YES ',
        ' n '
    ]
}
df = pd.DataFrame(data)
df['payment_status'] = df['payment_status'].str.strip().str.lower()
df['payment_status'] = df['payment_status'].replace({
    'yes': 1,
    'y': 1,
    'no': 0,
    'n': 0
})
df

  payment_status
0              1
1              1
2              1
3              0
4              0
5              0
6              1
7              0