In [5]:
import pandas as pd

ts=['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']
ts=pd.to_datetime(ts)
ts

DatetimeIndex(['2024-06-01 14:30:00', '2024-06-02 09:15:00',
               '2024-06-03 20:45:00'],
              dtype='datetime64[us]', freq=None)

In [10]:
df=pd.read_csv('restaurant_orders.csv')
df['Order_Date']=pd.to_datetime(df['Order_Date'])
df['year'] = df['Order_Date'].dt.year
df['month'] = df['Order_Date'].dt.month
df['weekday'] = df['Order_Date'].dt.day_name()
df

    Restaurant_Name Order_Date  year  month    weekday
0      Spice Garden 2026-08-01  2026      8   Saturday
1       Tasty Bites 2026-08-02  2026      8     Sunday
2        Urban Cafe 2026-08-02  2026      8     Sunday
3  Royal Restaurant 2026-08-03  2026      8     Monday
4        Green Leaf 2026-08-04  2026      8    Tuesday
5     Food Junction 2026-08-05  2026      8  Wednesday
6      The Food Hub 2026-08-06  2026      8   Thursday
7        Desi Zaika 2026-08-07  2026      8     Friday
8      Pizza Corner 2026-08-08  2026      8   Saturday
9     Fresh Kitchen 2026-08-09  2026      8     Sunday

In [12]:
df=pd.read_csv('flipkart_orders.csv')
df['order_date'] = pd.to_datetime(df['order_date'])
df.set_index('order_date', inplace=True)
weekly_orders = df.resample('W').size().reset_index(name='total_orders')
df

                     order_id       product_name
order_date
2024-06-01 14:30:00      1001     Wireless Mouse
2024-06-02 09:15:00      1002         Smartphone
2024-06-03 20:45:00      1003    Laptop Backpack
2024-06-04 11:20:00      1004  Bluetooth Speaker
2024-06-05 16:10:00      1005           Keyboard
2024-06-07 10:05:00      1006         Power Bank
2024-06-09 18:30:00      1007         Smartwatch
2024-06-10 12:45:00      1008          USB Cable
2024-06-12 15:20:00      1009         Headphones
2024-06-14 19:10:00      1010       Laptop Stand
2024-06-16 08:40:00      1011     Wireless Mouse
2024-06-17 13:25:00      1012  Bluetooth Speaker
2024-06-19 17:50:00      1013         Smartphone
2024-06-21 10:15:00      1014           Keyboard
2024-06-23 21:00:00      1015         Power Bank
2024-06-24 09:45:00      1016         Smartwatch
2024-06-26 14:10:00      1017         Headphones
2024-06-28 18:20:00      1018          USB Cable
2024-06-29 11:35:00      1019       Laptop Stand
2024-06-30 16:55:00      1020           Backpack

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/luminati-io/Social-media-dataset-samples/main/Instagram-datasets.csv')
df['comment_date'] = pd.to_datetime(df['comment_date'], utc=True)
df['comment_date'] = df['comment_date'].dt.tz_convert('Asia/Kolkata')
df['comment_date'].head()

0   2024-11-14 01:31:57+05:30
1   2024-11-13 22:41:39+05:30
2   2024-11-14 04:30:46+05:30
3   2024-11-14 05:46:19+05:30
4   2024-11-14 23:03:11+05:30
Name: comment_date, dtype: datetime64[us, Asia/Kolkata]

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/supermarket_sales.csv')
df["Date"] = pd.to_datetime(df["Date"])
df["is_weekend"] = df["Date"].dt.dayofweek >= 5
df[["Date", "is_weekend"]]

          Date  is_weekend
0   2019-01-05        True
1   2019-03-08       False
2   2019-03-03        True
3   2019-01-27        True
4   2019-02-08       False
..         ...         ...
995 2019-01-29       False
996 2019-03-02        True
997 2019-02-09        True
998 2019-02-22       False
999 2019-02-18       False

[1000 rows x 2 columns]